from getpass import getpass
import psycopg2
from psycopg2 import Error, connect

#uses python code to kind of dynamically get information and names
#probably not the best way, for future commands it will all be hard coded :)
#thought is if the database schema changes you should check and change code anyways... also might move to an ORM anyways and in that case the extra work is irrelevant

try:
    with connect(
        database = 'ETL_database',
        user='postgres',
        password=getpass("Enter password: "),
        host='localhost'
    ) as connection:
        
        with connection.cursor() as cursor:

            def get_column_names(table):
                #get all the column names
                column_names_query = f"""
                SELECT column_name, data_type
                FROM information_schema.columns
                WHERE table_name = '{table}'
                ;
                """
                cursor.execute(column_names_query)
                #cursor.execute(data_type_columns_query)
                column_names = cursor.fetchall()
                
                #remove autogenerated columns, just id and timestamps
                cols = [c for c in column_names if c[0] != 'id' if c[1] != 'timestamp without time zone']
                return cols
            
            def add_data(table,column_names, input_data):

                str_cols = ",".join([c[0] for c in column_names]) #list comprehension because it is a list of tuples (name,data_type)
                flags = ('%s,'*len(input_data))[:-1] #:-1 removes the last comma
                tup_input_data = tuple(input_data)

                add_data_query = f"""
                INSERT INTO "{table}" ({str_cols})
                VALUES ({flags})
                """
                cursor.execute(add_data_query,tup_input_data)
                return
            
            def find_id(table,column): #unique column!
                columnFound = False
                while columnFound == False:
                    column_input = input(f'Input {column}: ')

                    find_id_query = f'SELECT "id" FROM "{table}" WHERE {column}=%s'
                    cursor.execute(find_id_query,(column_input,))
                    id = cursor.fetchall()

                    if len(id) == 0:
                        print(f"{column_input} does not exist in database, try again")
                        continue
                    else:
                        columnFound = True
                
                return id[0][0] #integer!
            
            def check_serial_number(table,serial_column):
                #takes input serial number and checks it is doesn't excist already!
                unique = False
                while unique == False:

                    test_serial = input(f"Input {serial_column} : ")

                    check_unique_module_query = f"""
                    SELECT {serial_column} FROM "{table}";
                    """
                    cursor.execute(check_unique_module_query)
                    all_serial_nums = [i[0] for i in cursor.fetchall()]

                    if test_serial not in all_serial_nums:
                        unique=True
                    else:
                        print("component already exists, try again")
                    
                return test_serial

            the_table = 'component'
            
            #get all the column names
            columns = get_column_names(the_table)
            
            #get user data
            input_data = []
            for col in columns: #loop is silly but gets input_data list in the same order so the data matches column name
                if col[0] == 'component_serial_number':
                    #make sure that inputted serial number doesn't already exist!
                    input_data.append(check_serial_number(the_table,'component_serial_number'))
                    continue
                
                elif col[0] == 'module_id':
                    input_data.append(find_id('module','module_serial_number')) #read like find the id for the module with this module_serial_number
                    continue

                elif col[0] == 'component_type_id':
                    input_data.append(find_id('component_type_lookup','component_name'))
                    continue

                user_input = input(f"Input {col[0]} ({col[1]}): ")
                input_data.append(user_input)

            add_data(the_table,columns,input_data)


except Error as e:
    print(e)